config/routes.rb
Rails.application.routes.draw do
  root 'outils#choix'
  get 'login', to: 'outils#login'
  get 'search', to: 'outils#search'
  get 'find', to: 'outils#find'
  get 'prosearch', to: 'pro#search'
  get 'profind', to: 'pro#find'
  get 'index', to: 'outils#index'
  resources :outils

end

app/models/outil.rb
class Outil < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/outils_controller.rb
class OutilsController < ApplicationController
  before_action :set_outil, only: [:show, :edit, :update, :destroy]

  # GET /outils
  # GET /outils.json
  def index
  end

  # GET /outils/1
  # GET /outils/1.json
  def show
  end

  # GET /outils/new
  def new
    @outil = Outil.new
  end

  # GET /outils/1/edit
  def edit
  end

  # POST /outils
  # POST /outils.json
  def create
  end

  # PATCH/PUT /outils/1
  # PATCH/PUT /outils/1.json
  def update
  end

  # DELETE /outils/1
  # DELETE /outils/1.json
  def destroy
  end

  def login
  end

  def search
  end

  def find
  end

  def choix
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_outil
      @outil = Outil.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outil_params
      params.require(:outil).permit(:user)
    end
end

app/controllers/pro_controller.rb
class ProController < ApplicationController
  def index
  end
  
  def search
  end

  def find
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/outils_helper.rb
module OutilsHelper
end

app/views/outils/choix.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_path %>" style='font-family:expletus_sansmedium'>LawMine</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav" style='font-family: expletus_sansregular'>
                <li style=''>
                </li>
                <li style=''>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right" style='font-family: expletus_sansregular'>
                <li style=''>
                </li>
              </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<div class='container-fluid home' >
  <div class='container'>
    <div class='row ' style='margin-top:250px;width: 100%'>
      <div class='col-lg-12 center-block' style='text-align:left;'>
      <span style='margin-right: 20px;margin-bottom: 25px; padding-top:10px;font-size: 50px;color:white;font-family: expletus_sansmedium;'> Je suis </span>
<div style='margin-top: 20px;' >
        <a href="<%= index_path %>" class='btn btn-default' style=' width: 190px;; margin-right: 100px;border-radius: 50px;' >
          Professionnel du droit
        </a>
        <a href="<%= find_path %>" class='btn btn-default' style='width: 190px;border-radius: 50px; '>
          Particulier/Entreprise
        </a>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/outils/edit.html.erb
<h1>Editing outil</h1>

<%= render 'form' %>

<%= link_to 'Show', @outil %> |
<%= link_to 'Back', outils_path %>

app/views/outils/find.html.erb
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>
<script>
$(function () {
    $('#cam').highcharts({
        chart: {
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45,
                beta: 0
            }
        },
        title: {
            text: 'Taux de gain de cause '
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 35,
                dataLabels: {
                    enabled: true,
                    format: '{point.name}'
                }
            }
        },
        series: [{
            type: 'pie',
            name: '',
            data: [
                ['Echec', 14.2],
                ['Succès', 85.8],
            ]
        }]
    });
});


$(function () {
    $('#histo').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Indemnisation en fonction du salaire (euros)'
        },
        xAxis: {
            type: 'category',
            labels: {
                rotation: -45,
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif'
                }
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Indémnisation'
            }
        },
        legend: {
            enabled: false
        },
        tooltip: {
            pointFormat: 'Indémnisation: <b>{point.y:.1f} mille euros</b>'
        },
        series: [{
            name: 'Population',
            data: [
                ['< 2 500', 10.7],
                ['< 3 500', 20.1],
                ['< 4 500', 34.2],
                ['< 5 000', 40.0],
            ],
            dataLabels: {
                enabled: true,
                rotation: -90,
                color: '#FFFFFF',
                align: 'right',
                format: '{point.y:.1f}', // one decimal
                y: 10, // 10 pixels down from the top
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif'
                }
            }
        }]
    });
});
</script>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_path %>" style='font-family:expletus_sansmedium'>LawMine</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav" style='font-family: expletus_sansregular'>
                <li style=''>
                  <%= link_to "Recherche", prosearch_path %>
                </li>
                <li style=''>
                  <%= link_to "Mes recherches", search_path %>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right" style='font-family: expletus_sansregular'>
                <li style=''>
                  <%= link_to "Connection", login_path %>
                </li>
              </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<div class='container' style='font-family:expletus_sansregular;'>
  <h2 style='font-family:expletus_sansmedium; margin-bottom: 25px;'> Résultats de la recherche</h2>
  <div id="cam" style="min-width: 300px; height: 400px; margin-top: 45px;"></div>
<hr style='margin-top: 15px; margin-bottom:15px;'>
  <div id="histo" style="min-width: 300px; height: 400px; margin-top: 45px;"></div>
</div>

app/views/outils/index.html.erb
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_path %>" style='font-family:expletus_sansmedium'>LawMine</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav" style='font-family: expletus_sansregular'>
                <li style=''>
                  <%= link_to "Recherche", prosearch_path %>
                </li>
                <li style=''>
                  <%= link_to "Mes recherches", search_path %>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right" style='font-family: expletus_sansregular'>
                <li style=''>
                  <%= link_to "Connection", prosearch_path %>
                </li>
              </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<div class='container-fluid' style='padding: 0;'>
<header class="business-header">
      <div class="container">
          <div class="row">
              <div class="col-lg-12">
                <h1 class="tagline" style='font-family:expletus_sansmedium; margin-top: 40px;'>LAWMINE</h1><h2 style='color: white; font-family:expletus_sansmedium; margin-top: -15px;margin-left: 15px'>Smarter data, smarter lawyers</h2>
              </div>
          </div>
      </div>
  </header>
</div>

  <!-- Page Content -->
  <div class="container" style='margin-top: 15px;'>
      <div class="row">
          <div class="col-sm-8">
            <h2>Que fait-on?</h2>
            <br>
            <p style='margin-left: 20px;'>LawMine est le partenaire optimal de l’avocat, en conseil comme en contentieux.<br> 
            Nous récoltons et analysons toutes les juridictions disponibles en France afin de vous aider à évaluer le risque judiciaire et les dommages et intérêts habituellement liés à une affaire comparable à la vôtre.</p>
            <p style='margin-left: 20px;'>LawMine, pour un meilleur assessment du risque judiciaire et de votre position de négociation, tous les jours, dans chacune de vos affaires.  </p>
          </div>
          <div class="col-sm-4">
            <h2>Avantages </h2>
            <br>
            <ul>
               <li>Gain de temps</li><br>
               <li>Meilleur connaissance du risque</li><br>
               <li>Aide à la décision</li>
            </ul>
          </div>
      </div>
      <!-- /.row -->
      <hr>

      <div class="row">
          <div class="col-sm-4">
            <img class="img-circle img-responsive img-center" src=<%= image_path('bigdata.jpeg') %> style='height:300px; width: 300px'>
              <h2>1. Big Data</h2>
              <p>Nous agrégeons et uniformisons les jugements disponibles dans une base de données unique </p>
          </div>
          <div class="col-sm-4">
            <img class="img-circle img-responsive img-center" src=<%= image_path("smartdata.jpeg") %> style='height:300px; width: 300px'>
              <h2>2. Smart Data</h2>
              <p>Nous traitons et critérisons cette base de données de façon à en extraire des statistiques et des tendances</p>
          </div>
          <div class="col-sm-4">
              <img class="img-circle img-responsive img-center" src=<%= image_path("smartlawyer.png") %> style='height:300px; width: 300px' alt="">
              <h2>3. Smart Lawyer</h2>
              <p>Vous identifiez l’angle spatio-temporel et les critères juridiques de votre choix, et nous vous restituons un benchmark des tendances de jugements associés, pour vous offrir un cadre de référence intelligent.</p>
          </div>
      </div>
      <hr>
    </div>
      <!-- /.row -->

app/views/outils/new.html.erb
<h1>New outil</h1>

<%= render 'form' %>

<%= link_to 'Back', outils_path %>

app/views/outils/search.html.erb
<script>
$(document).ready(function(){
    $(".litige").hide();
    $(".pro").hide();
    $(".prudhomme").click(function(){
        $(".litige").show();
    });
    $(".checkpro").click(function(){
        $(".pro").show();
    });
});
</script>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_path %>" style='font-family:expletus_sansmedium'>LawMine</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav" style='font-family: expletus_sansregular'>
                <li style=''>
                  <%= link_to "Recherche", prosearch_path %>
                </li>
                <li style=''>
                  <%= link_to "Mes recherches", search_path %>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right" style='font-family: expletus_sansregular'>
                <li style=''>
                  <%= link_to "Connection", login_path %>
                </li>
              </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


<div class='container'  style='font-family:expletus_sansmedium;'>
  <h1 class='title-filter'>Filtres de recherche</h1>

  <div class='row center-block f1'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6 '>
      <h3>Contentieux</h3>
        <label class="checkbox-inline checkpro"><input type="checkbox" value="">Professionnel</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Privé</label>
      <div class='row center-block f1 pro'>
        <label class="checkbox-inline ici"><input type="checkbox" value="">Salarié</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Indépendant</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Employeur</label>
      </div>
    </div>
  </div>

  <div class='row center-block f1'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6'>
      <h3>Parties prenantes</h3>
      <div class="form-group">
         <label class="checkbox-inline"><input type="checkbox" value=""> Entreprise vs Entreprise</label>
         <label class="checkbox-inline"><input type="checkbox" value="">Entreprise vs salarié</label>
         <label class="checkbox-inline prudhomme"><input type="checkbox" value="">Autre</label>
      </div>
    </div>
  </div>

  <div class='row center-block f1 litige'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6 '>
      <h3>Litiges</h3>
        <label class="checkbox-inline"><input type="checkbox" value="">Salaires impayés</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Demande d'indemnité</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Contestation d'une sanction</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Licenciement abusif</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Discrimination</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Autre</label>
    </div>
  </div>

  <div class='row center-block f1'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6 '>
      <h3>Je voudrais</h3>
        <label class="checkbox-inline"><input type="checkbox" value="">Taux de succès</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Taux d'indémnisation</label>
    </div>
  </div>

  <div class='row center-block'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6'>
      <h3>Mots-clés</h3>
        <div class="form-group">
          <textarea class="form-control" placeholder='Licenciement sans faute, CDI ...' ></textarea>
        </div>
    </div>
  </div>

  <div class='row center-block'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6'>
      <a href='<%= find_path %>' class="btn btn-default center-blok" role="button"> Chercher </a>
    </div>
  </div>
<div>

app/views/outils/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @outil.user %>
</p>

<%= link_to 'Edit', edit_outil_path(@outil) %> |
<%= link_to 'Back', outils_path %>

app/views/pro/find.html.erb
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>

<script>
$(function () {
    $('#bathor').highcharts({
        chart: {
            type: 'bar'
        },
        title: {
            text: 'Taux de condamnation'
        },
        xAxis: {
            categories: ['Rupture anticipée de contrat']
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Total sur 2400 dossiers'
            }
        },
        legend: {
            reversed: true
        },
        plotOptions: {
            series: {
                stacking: 'normal'
            }
        },
        series: [{
            name: 'Condamné',
            data: [70]
        }, {
            name: 'Non condamné',
            data: [30]
        }]
    });
});


$(function () {
    $('#combi').highcharts({
        title: {
            text: 'Sanction financière en fonction de celle exigée par le plaignant'
        },
        xAxis: {
            categories: ['0 %', '0 - 10 %', '10 - 30 %', '30 - 50%', '50 - 75%', '75 - 100 %']
        },
        labels: {
            items: [{
                html: 'Total sanctions financières',
                style: {
                    left: '50px',
                    top: '18px',
                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'black'
                }
            }]
        },
        series: [{
            type: 'column',
            name: '2010',
            data: [3, 2, 1, 3, 4]
        }, {
            type: 'column',
            name: '2011',
            data: [2, 3, 5, 7, 6]
        }, {
            type: 'column',
            name: '2012',
            data: [4, 3, 3, 9, 0]
        }, {
            type: 'spline',
            name: 'Average',
            data: [3, 2.67, 3, 6.33, 3.33],
            marker: {
                lineWidth: 2,
                lineColor: Highcharts.getOptions().colors[3],
                fillColor: 'white'
            }
        }, {
            type: 'pie',
            name: 'Total consumption',
            data: [{
                name: 'Jane',
                y: 13,
                color: Highcharts.getOptions().colors[0] // Jane's color
            }, {
                name: 'John',
                y: 23,
                color: Highcharts.getOptions().colors[1] // John's color
            }, {
                name: 'Joe',
                y: 19,
                color: Highcharts.getOptions().colors[2] // Joe's color
            }],
            center: [100, 80],
            size: 100,
            showInLegend: false,
            dataLabels: {
                enabled: false
            }
        }]
    });
});

$(function () {
    $('#cam').highcharts({
        chart: {
            type: 'pie',
            options3d: {
                enabled: true,
                alpha: 45,
                beta: 0
            }
        },
        title: {
            text: 'Articles invoqués lors du procès'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                depth: 35,
                dataLabels: {
                    enabled: true,
                    format: '{point.name}'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Article du droit',
            data: [
                ['Article L442-6', 45.0],
                ['Article L121-3', 26.8],
                {
                    name: 'Article L121-3',
                    y: 12.8,
                    sliced: true,
                    selected: true
                },
                ['Article L441-6', 8.5],
                ['Article L310-3', 6.2],
                ['Others', 0.7]
            ]
        }]
    });
});
</script>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_path %>" style='font-family:expletus_sansmedium'>LawMine</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav" style='font-family: expletus_sansregular'>
                <li style=''>
                  <%= link_to "Recherche", prosearch_path %>
                </li>
                <li style=''>
                  <%= link_to "Mes recherches", search_path %>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right" style='font-family: expletus_sansregular'>
                <li style=''>
                  <%= link_to "Julie Delrieu", login_path %>
                </li>
              </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<div class='container' style='margin-top:25px;'>
  <h1 style='margin-bottom: 25px; font-family: expletus_sansmedium'> Analyse statistique </h1>
  <div id="bathor" style="min-width: 300px; height: 400px;margin-top: 35px; "></div>
<hr>
  <div id="cam" style="min-width: 300px; height: 400px; margin-top: 45px;"></div>
<hr>
  <div id="combi" style="min-width: 300px; height: 400px;margin-top:45px "></div>
<div style='margin-top: 30px;'>
    <a href="#" target='_blank' style='color: blue; text-decoration:underline; padding-right: 20px;'> Enregistrer dans 'mes recherches'</a>
    <a href="#" target='_blank' style='color: blue; text-decoration:underline; padding-right: 20px;'> Rapport détaillé</a>
    <a href= '<%= image_path('Ferrari.pdf') %>' target='_blank' style='color: blue; text-decoration:underline'> Décisions associées</a>
</div>
</div>

app/views/pro/search.html.erb
<script>
$(document).ready(function(){
    $(".entreprise").hide();
    $(".forlawyer").hide();
    $(".prive").hide();
    $(".affaire").hide();
    $(".commerce").click(function(){
        $(".entreprise").show();
    });
    $(".avocat").click(function(){
        $(".forlawyer").show();
    });
    $(".checkprive").click(function(){
        $(".prive").show();
    });
    $(".checkaffaire").click(function(){
        $(".affaire").show();
    });
});
</script>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_path %>" style='font-family:expletus_sansmedium'>LawMine</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav" style='font-family: expletus_sansregular'>
                <li style=''>
                  <%= link_to "Recherche", prosearch_path %>
                </li>
                <li style=''>
                  <%= link_to "Mes recherches", search_path %>
                </li>
              </ul>
              <ul class="nav navbar-nav navbar-right" style='font-family: expletus_sansregular'>
                <li style=''>
                  <%= link_to "Julie Delrieu", login_path %>
                </li>
              </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<div class='container'  style='font-family:expletus_sansmedium;'>
  <h1 class='title-filter'>Filtres de recherche</h1>


  <div class='row center-block f1'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6 '>
      <h3>Je voudrais</h3>
        <label class="checkbox-inline"><input type="checkbox" value="">Une estimation de prix</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Un volume d'affaires</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Un taux de condamnation</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Un rapport complet et détaillé</label>
    </div>
  </div>
  
  <div class='row center-block f1'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6'>
      <h3>Type de droit</h3>
      <div class="form-group">
         <label class="checkbox-inline checkprive"><input type="checkbox" value=""> Privé</label>
         <label class="checkbox-inline "><input type="checkbox" value="">Public</label>
        <div class='prive'>
           <label class="checkbox-inline prive"><input type="checkbox" value=""> Droit civil</label>
           <label class="checkbox-inline prive"><input type="checkbox" value=""> Droit international</label>
           <label class="checkbox-inline prive checkaffaire"><input type="checkbox" value=""> Droit des affaires</label>
           <label class="checkbox-inline prive"><input type="checkbox" value=""> Droit économique</label>
        </div>
        <div class='affaire'>
         <select>
            <option value="volvo">Droit commercial</option>
            <option value="saab">Droit des societés</option>
            <option value="mercedes">Droit social/travail</option>
            <option value="audi">Droit des entreprises en difficulté</option>
            <option value="audi">Droit de la concurrence</option>
            <option value="audi">Droit de la consommation</option>
            <option value="audi">Droit bancaire/assurance</option>
            <option value="audi">Droit financier</option>
          </select>
        </div>
      </div>
    </div>
  </div>
  <div class='row center-block f1'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6'>
      <h3>Type de tribunal</h3>
      <div class="form-group">
         <label class="checkbox-inline commerce"><input type="checkbox" value=""> Tribunal de Commerce</label>
         <label class="checkbox-inline prudhomme"><input type="checkbox" value="">Conseil Prud'hommes</label>
         <label class="checkbox-inline"><input type="checkbox" value="">Tribunal d'Instance</label>
         <label class="checkbox-inline"><input type="checkbox" value=""> Tribunal de Grande Instance</label>
      </div>
    </div>
  </div>

  <div class='row center-block f1 entreprise'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6'>
      <h4> Chiffre d'affaires de l'entreprise attaquée(euros) </h4>
          <select class="form-control" id="sel1">
            <option> 0 - 100 000</option>
            <option> 100 000 - 1 000 000</option>
            <option> 1 000 000 - 5 000 000</option>
            <option> + 5 000 000</option>
          </select>
    </div>
  </div>
  
  <div class='row center-block f1 litige'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6 '>
      <h3>Type de litige</h3>
        <label class="checkbox-inline"><input type="checkbox" value="">Salaires impayés</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Demande d'indemnité</label>
        <label class="checkbox-inline"><input type="checkbox" value="">Contestation d'une sanction</label>
    </div>
  </div>

  <div class='row center-block f1'>
    <div class='col-lg-3'> </div>
    <div class='col-lg-6'>
      <h3>Période</h3>
        De</><br>
        <textarea rows="2" cols="15" placeholder='Mois'></textarea>
        <textarea rows="2" cols="6" placeholder='Année'></textarea>
        <br>A</><br>
        <textarea rows="2" cols="15" placeholder='Mois'></textarea>
        <textarea rows="2" cols="6" placeholder='Année'></textarea>
    </div>
  </div>

  <div class='row center-block f1'>
      <div class='col-lg-3'></div>
      <div class='col-lg-6 '>
        <h3>Couverture géographique</h3>
          <label class="checkbox-inline"><input type="checkbox" value="">Paris</label>
          <label class="checkbox-inline"><input type="checkbox" value="">Nanterre</label>
          <label class="checkbox-inline"><input type="checkbox" value="">Versailles</label>
      </div>
    </div>


  <div class='row center-block forlawyer'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6'>
      <h3>Code, article de loi</h3>
        <div class="form-group">
          <textarea class="form-control" ></textarea>
        </div>
    </div>
  </div>

  <div class='row center-block'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6'>
      <h3>Mots-clés</h3>
        <div class="form-group">
          <textarea class="form-control" ></textarea>
        </div>
    </div>
  </div>

  <div class='row center-block'>
    <div class='col-lg-3'></div>
    <div class='col-lg-6'>
      <a href='<%= profind_path %>' class="btn btn-default center-blok" role="button"> Chercher </a>
    </div>
  </div>
<div>